version: '3.9'

services:
  # ZooKeeper Cluster
  zk1:
    container_name: zk1
    hostname: zk1
    image: bitnami/zookeeper:3.6.2
    ports:
      - 21811:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=1
      - ZOO_SERVERS=0.0.0.0:2888:3888,zk2:2888:3888,zk3:2888:3888

  zk2:
    container_name: zk2
    hostname: zk2
    image: bitnami/zookeeper:3.6.2
    ports:
      - 21812:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=2
      - ZOO_SERVERS=zk1:2888:3888,0.0.0.0:2888:3888,zk3:2888:3888

  zk3:
    container_name: zk3
    hostname: zk3
    image: bitnami/zookeeper:3.6.2
    ports:
      - 21813:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=3
      - ZOO_SERVERS=zk1:2888:3888,zk2:2888:3888,0.0.0.0:2888:3888

  # Zoonavigator (UI for Zookeeper)
  zoonavigator:
    container_name: zoonavigator
    image: elkozmon/zoonavigator
    ports:
      - 9000:9000

  # DynamoDB Local for Testing
  ddb:
    image: amazon/dynamodb-local
    container_name: ddb
    ports:
      - 8000:8000

  # Backend Services
  backend1:
    build: .
    container_name: backend1
    environment:
      - SERVER_ID=1
    depends_on:
      - ddb
      - zk1
      - zk2
      - zk3

  backend2:
    build: .
    container_name: backend2
    environment:
      - SERVER_ID=2
    depends_on:
      - ddb
      - zk1
      - zk2
      - zk3

  backend3:
    build: .
    container_name: backend3
    environment:
      - SERVER_ID=3
    depends_on:
      - ddb
      - zk1
      - zk2
      - zk3

  # NGINX Service
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - backend2
      - backend3
