version: '3.8'

services:
  zoo1:
    image: zookeeper:3.8.2
    hostname: zoo1
    container_name: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

  zoo2:
    image: zookeeper:3.8.2
    hostname: zoo2
    container_name: zoo2
    ports:
      - "2182:2181"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

  zoo3:
    image: zookeeper:3.8.2
    hostname: zoo3
    container_name: zoo3
    ports:
      - "2183:2181"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

  backend1:
    build: .
    container_name: backend1
    environment:
      - SERVER_ID=1
    depends_on:
      - ddb
      - zoo1
      - zoo2
      - zoo3

  backend2:
    build: .
    container_name: backend2
    environment:
      - SERVER_ID=2
    depends_on:
      - ddb
      - zoo1
      - zoo2
      - zoo3

  backend3:
    build: .
    container_name: backend3
    environment:
      - SERVER_ID=3
    depends_on:
      - ddb
      - zoo1
      - zoo2
      - zoo3

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - backend2
      - backend3

  ddb:
    image: amazon/dynamodb-local
    container_name: ddb
    ports:
      - "8003:8000"
